certificate-transparency:
  target-domains:
    - 'sans.org'
  filter-domains:
    - 'None'
perimeter-monitoring:
  target-hosts:
    - 'sans.org'
shodan-monitoring:
  target-keyword:
    - 'sans.org'
cloud-enumeration:
  target-keyword:
    - 'securityonion'
  filter-domains:
    - 'None'
